# Site settings
author: Roberto Livi
title: Flatiron Experience
header-img: img/home-bg.png
email: robertomlivi@outlook.com
copyright_name: Roberto Livi
description: > # this means to ignore newlines until "baseurl:"
  Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Roberto-Livi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
